name: Publish to DockerHub

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - id: commit
              uses: pr-mpt/actions-commit-hash@v2
            - uses: actions/checkout@v2
            - name: docker login
              env:
                  DOCKER_USER: ${{secrets.DOCKER_USER}}
                  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
              run: |
                  docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            - name: Build the Docker image
              run: docker build . --file Dockerfile --tag eeriksen/pdf-tools:latest --tag eeriksen/pdf-tools:${{ steps.commit.outputs.short }}

            - name: Docker Push
              run: docker push eeriksen/pdf-tools --all-tags
