name: Publish to DockerHub

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write # Required to push tags
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Semantic version
              id: semver
              uses: paulhatch/semantic-version@v5.4.0
              with:
                  tag_prefix: "v"
                  major_pattern: "/^feat(\\([\\w\\-\\.]+\\))?!: ([\\w ])+([\\s\\S]*)$/"
                  minor_pattern: "/^feat(\\([\\w\\-\\.]+\\))?: ([\\w ])+([\\s\\S]*)$/"
                  version_format: ${major}.${minor}.${patch}
                  enable_prerelease_mode: false
                  search_commit_body: true
                  bump_each_commit: true

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to Docker Hub
              env:
                  DOCKER_USER: ${{secrets.DOCKER_USER}}
                  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
              run: |
                  docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                  context: .
                  platforms: linux/amd64,linux/arm64
                  push: true
                  tags: eeriksen/pdf-tools:latest, eeriksen/pdf-tools:${{ steps.semver.outputs.version }}

            - name: Create and push tag
              if: github.event_name == 'push'
              run: |
                  git tag "v${{ steps.semver.outputs.version }}"
                  git push origin "v${{ steps.semver.outputs.version }}"
